{{- if .Values.defaultEgressPolicyDeleter.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default-egress-policy-deleter
  namespace: ct-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: default-egress-policy-deleter
rules:
- apiGroups: ["networking.gke.io"]
  resources: ["egressnatpolicies"]
  verbs: ["delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: default-egress-policy-deleter
  namespace: ct-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: default-egress-policy-deleter
subjects:
- kind: ServiceAccount
  name: default-egress-policy-deleter
  namespace: ct-system
---
apiVersion: batch/v1
kind: Job
metadata:
  name: default-egress-policy-deleter
  namespace: ct-system
spec:
  template:
    spec:
      serviceAccountName: default-egress-policy-deleter
      containers:
      - name: deleter
        image: google/cloud-sdk:latest
        command: ["/bin/sh",  "-c", "kubectl delete --ignore-not-found egressnatpolicies default"]
      restartPolicy: Never
  backoffLimit: 3
{{- end }}
